import InputField from '../../../components/InputField';
import SectionCard from '../../../components/SectionCard';
import ChoiceChips from './ChoiceChips';

const EmployeePersonalDetails = ({ form, errors, setField, setGender, setMaritalStatus }) => (
  <SectionCard title="Personal details">
    <div className="grid gap-4 sm:grid-cols-2">
      <InputField label="Employee code" value={form.employee_code} helperText="Generated by the server." disabled />
      <InputField label="Full name" value={form.name} onChange={setField('name')} error={errors.name} required />
      <InputField label="Date of birth" type="date" value={form.dob} onChange={setField('dob')} error={errors.dob} />
      <ChoiceChips label="Gender" value={form.gender} options={['Male', 'Female', 'Other']} onChange={setGender} error={errors.gender} />
      <ChoiceChips label="Marital status" value={form.marital_status} options={['Single', 'Married', 'Divorced', 'Widowed']} onChange={setMaritalStatus} error={errors.marital_status} />
    </div>
  </SectionCard>
);

export default EmployeePersonalDetails;
